version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  server:
    image: jeongyeonjun/molly-server
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - network

networks:
  network: