version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  application:
    image: jeongyeonjun/docker-springboot
    environment:
      - MYSQL_HOST=molly-database.c3ytlezhswih.ap-northeast-2.rds.amazonaws.com
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=molly1234
      - MYSQL_DATABASE=mollydb
      - MYSQL_USER=root
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      - redis
    restart: always

  nginx:
    image: jeongyeonjun/docker-nginx
    ports:
      - "80:80"
    restart: "always"