version: "3.8"

services:
  application:
    image: jeongyeonjun/docker-springboot
    depends_on:
      - MYSQL_HOST=${{ secrets.RDS_END_POINT }}
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=molly1234
      - MYSQL_DATABASE=mollydb
      - MYSQL_USER=root
    restart: always

  nginx:
    image: jeongyeonjun/docker-nginx
    ports:
      - "80:80"
    restart: "always"